### ISSUE TITLE
assets folder is missing

### ISSUE THREAD

**Issue by ddrm86** [opencodenitr/hephaestus#8]
It looks like the game needs an assets folder that is currently missing from the repository:

```
Traceback (most recent call last):
  File "C:/Users/sotan/PycharmProjects/hephaestus/Star Wars Lite/main.py", line 6, in <module>
    from structs import elements, root, sprites
  File "C:\Users\sotan\PycharmProjects\hephaestus\Star Wars Lite\structs\elements.py", line 6, in <module>
    from structs import sprites
  File "C:\Users\sotan\PycharmProjects\hephaestus\Star Wars Lite\structs\sprites.py", line 7, in <module>
    ENEMY0 = pygame.image.load(r"assets\enemy1.png")
pygame.error: Couldn't open assets\enemy1.png

Process finished with exit code 1
```

**Comment by 007vedant** [comment]
Hi @ddrm86, I have added the assets directory to the game repo via PR #9 . Please pull from the main. Meanwhile, I'll assign the other issue to you.
